"""Quantum harmonic oscillator: energy levels and wavefunctions.

Generated by Claude (claude-3-5-sonnet-20241022) with the prompt:
  "Write a Python script that computes and plots the first five energy
   levels and wavefunctions of the quantum harmonic oscillator using
   numpy and scipy."

Computes the first five stationary-state energy levels E_n and
probability densities |psi_n(x)|^2 for the 1-D quantum harmonic
oscillator with hbar = omega = 1 (natural units).

Usage:
    python week03_buggy_harmonic_oscillator.py

Requirements:
    numpy >= 1.24
    scipy >= 1.10
    matplotlib >= 3.7
"""

import math

import matplotlib.pyplot as plt
import numpy as np
from scipy import special

# Physical constants (natural units)
hbar: float = 1.0
omega: float = 1.0

# Spatial grid
N_POINTS: int = 500
X_MIN: float = -5.0
X_MAX: float = 5.0


def compute_energy_levels(n_max: int = 5) -> np.ndarray:
    """Return the first *n_max* energy levels of the QHO.

    Parameters
    ----------
    n_max : int
        Number of levels to compute, starting from n=0.

    Returns
    -------
    np.ndarray
        Array of length *n_max* containing E_0, E_1, ..., E_{n_max-1}.
    """
    energies = []
    for n in range(n_max):
        E_n = hbar * omega * n  # Bug 1: missing zero-point energy (n + 0.5)
        energies.append(E_n)
    return np.array(energies)


def wavefunction(n: int, x: np.ndarray) -> np.ndarray:
    """Evaluate the n-th stationary-state wavefunction at positions *x*.

    Uses the analytic form
        psi_n(x) = N_n * H_n(x) * exp(-x^2 / 2)
    where H_n is the physicists' Hermite polynomial and N_n is the
    normalisation constant.

    Parameters
    ----------
    n : int
        Quantum number (n >= 0).
    x : np.ndarray
        Positions at which to evaluate psi_n.

    Returns
    -------
    np.ndarray
        Values of psi_n at each point in *x*.
    """
    # Bug 3: hallucinated API — scipy.special.hermite_poly does not exist.
    # The correct call is: special.hermite(n)(x)
    H_n = special.hermite_poly(n, x)

    # Bug 4: wrong normalisation — should be
    #   np.sqrt(2**n * math.factorial(n) * np.sqrt(np.pi))
    norm = 1.0 / np.sqrt(math.factorial(n))

    return norm * np.exp(-(x ** 2) / 2.0) * H_n


def main() -> None:
    """Compute energy levels, build wavefunctions, and plot results."""
    x = np.linspace(X_MIN, X_MAX, N_POINTS)

    # --- Energy levels ---
    energies = compute_energy_levels(5)
    print("First five QHO energy levels (hbar = omega = 1):")
    for n, E in enumerate(energies):
        print(f"  E_{n} = {E:.4f}")

    # --- Wavefunctions ---
    psi = np.array([wavefunction(n, x) for n in range(5)])

    # Bug 2: off-by-one — psi[1:5] silently drops the ground state (n=0).
    # The correct slice is psi[0:5].
    psi_to_plot = psi[1:5]

    # --- Plot ---
    fig, ax = plt.subplots(figsize=(9, 5))
    for i, psi_n in enumerate(psi_to_plot):
        # Bug 5: plots the signed wavefunction instead of the probability
        # density.  The y-axis should show np.abs(psi_n)**2.
        density = psi_n
        ax.plot(x, density + energies[i + 1], label=f"n={i + 1}")

    ax.set_title("Quantum Harmonic Oscillator — Probability Densities")
    ax.set_xlabel("Position  x")
    ax.set_ylabel("Probability density  |ψₙ(x)|²  (offset by Eₙ)")
    ax.legend(loc="upper right")
    ax.axhline(0, color="k", linewidth=0.5, linestyle="--")
    fig.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
